stages:
  - test
  - bump
  - publish

test:
  only:
    - branches
  script:
    - npm install
    - npm run test:ci
  stage: test
  tags:
    - shell

whats_new:
  except:
    - master
  only:
    - branches
  script:
    - whats_new
  stage: test
  tags:
    - docker

bump_version:
  only:
    - master
  script:
    - bump2
  stage: bump
  tags:
    - docker

publish:
  only:
    - tags
  script:
    - npm install
    - npm run build
    - npm publish
  stage: publish
  tags:
    - shell

deploy_demoapp:
  only:
    - tags
  script:
    - npm install
    - npm run build
    - npm run build-demo-app
    - cp -r dist-demo-app/* /var/www/ratel-sdk-js-demo.local/
  stage: publish
  tags:
    - shell
