stages:
  - test
  - bump

test:
  only:
    - branches
  before_script:
    - cp $NPM_RC web-demo-app/.npmrc
  script:
    - docker build -t tmp .
  stage: test
  tags:
    - shell

whats_new:
  except:
    - master
  only:
    - branches
  script:
    - whats_new
  stage: test
  tags:
    - docker

bump_version:
  only:
    - master
  script:
    - bump2
  stage: bump
  tags:
    - docker